### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by jbadeau** [mkutz/shakespeare#27]
Hi,

I am currently working some Gauge modules (will make public in a few days) to make testing easier. I shamelessly use your code but I made some adjustments including:

- adding Cast, Stage and Director
- changing Fact to Memory and allowing to remember a question
- Adding pronoun support to actor
- basic assertion support but I will probably remove it.

I like the light approach and would like to support you. The serenity lib is way to big and confusing.

If you don't mind I would like to have a small chat (possibly video) and find out what your plans are and check if there is some way I can support you if the directions are aligned.

What do you think?

**Comment by mkutz** [comment]
Hi Jose,

sure, let's have a call. I'll send you an email later today.

Cheers
