### ISSUE TITLE
Actions/Interactions

### ISSUE THREAD

**Issue by jbadeau** [mkutz/shakespeare#67]
Hi again,

What is your view on [actions/interactions](https://serenity-js.org/handbook/design/interactions.html)?

> 
> Serenity/JS interactions are named using the vocabulary of the solution domain, so: "Click on a button", "Enter password into a form field" or "Send a request", and are focused on doing one thing and one thing only.
> 
> If you're considering implementing an interaction that performs more than one logical activity (i.e. checks if the button is visible and then clicks on it if is), consider implementing separate interactions for separate responsibilities and composing them together using a task.

I usually don't reference Serenity Java [core](https://github.com/serenity-bdd/serenity-core/tree/master/serenity-screenplay/src/main/java/net/serenitybdd/screenplay) as it's huge and way to complex for my liking.

The Serenity JS [core](https://github.com/serenity-js/serenity-js/tree/master/packages/core/src/screenplay) is much more compact and closer to Shakesphere.

I would like to provide out of the box actions/interactions 

```JavaScript
Actor.named('Ernest').whoCan(Log.the("Current page", Website.title(), Website.url()));
Actor.named('Ernest').whoCan(WriteToStream.of(process.stdout));
```

I would like to be able to create a busines level task which is composed of multiple interactions.

```JavaScript

// Task    
Actor.named('Ernest').whoCan(Create.Order(order));

// Actions
 actor.attemptsTo(
   Send.a(PostRequest.to('/orders/, order)),
   Ensure.that(LastResponse.status(), equals(200)),
   ...
 );

```

Would you consider adding this? Im pretty sure I will add it but wanted to first get your opinion.

**Comment by mkutz** [comment]
Shakespeare's Task interface is generally not limited to anything. You can group interactions (e.g. Selenium) into one Task implementation and they will be performed.

I'd define these Tasks as reusable implementations of Task, but you could also pass as Lambda.

```java
var user = new Actor();
user.does((actor) -> {
    var webDriver = actor.uses(BrowseTheWeb.class).getWebDriver();
    // … one or multiple interactions
});
```

It is also possible to do other Tasks within a Task.

```java
var user = new Actor();
user.does(new ComposedTask());
```

Generally you could also put assertions into a Task/Question.

Not sure if this is what you are looking for.
